# Generated by Django 5.0.7 on 2024-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_animal_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
