# Generated by Django 5.0.7 on 2024-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_mascota_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion',
            new_name='contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
