# Generated by Django 5.0.7 on 2024-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_rename_direccion_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='idUsuario', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
