# Generated by Django 5.0.7 on 2024-07-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_remove_usuario_id_usuario_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
